#############################################################################
# Makefile for building: linux/HIDBootloader
# Generated by qmake (2.01a) (Qt 4.8.1) on: Tue May 28 16:02:27 2013
# Project:  Bootloader.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile Bootloader.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_SQL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -Os -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtSql -I/usr/include/qt4 -I.. -Ilinux -Ilinux
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -L../HIDAPI/linux -lHIDAPI -lusb-1.0 -lQtSql -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = linux/

####### Files

SOURCES       = Settings.cpp \
		MainWindow.cpp \
		main.cpp \
		DeviceData.cpp \
		Device.cpp \
		Comm.cpp \
		ImportExportHex.cpp linux/moc_Settings.cpp \
		linux/moc_MainWindow.cpp \
		linux/moc_Comm.cpp \
		linux/qrc_resources.cpp
OBJECTS       = linux/Settings.o \
		linux/MainWindow.o \
		linux/main.o \
		linux/DeviceData.o \
		linux/Device.o \
		linux/Comm.o \
		linux/ImportExportHex.o \
		linux/moc_Settings.o \
		linux/moc_MainWindow.o \
		linux/moc_Comm.o \
		linux/qrc_resources.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		Bootloader.pro
QMAKE_TARGET  = HIDBootloader
DESTDIR       = linux/
TARGET        = linux/HIDBootloader

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): linux/ui_MainWindow.h linux/ui_Settings.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) linux/ || $(MKDIR) linux/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Bootloader.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/lib/x86_64-linux-gnu/libQtSql.prl \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile Bootloader.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/lib/x86_64-linux-gnu/libQtSql.prl:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile Bootloader.pro

dist: 
	@$(CHK_DIR_EXISTS) linux/HIDBootloader1.0.0 || $(MKDIR) linux/HIDBootloader1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) linux/HIDBootloader1.0.0/ && $(COPY_FILE) --parents Settings.h MainWindow.h DeviceData.h Device.h Comm.h ImportExportHex.h linux/HIDBootloader1.0.0/ && $(COPY_FILE) --parents resources.qrc linux/HIDBootloader1.0.0/ && $(COPY_FILE) --parents Settings.cpp MainWindow.cpp main.cpp DeviceData.cpp Device.cpp Comm.cpp ImportExportHex.cpp linux/HIDBootloader1.0.0/ && $(COPY_FILE) --parents MainWindow.ui Settings.ui linux/HIDBootloader1.0.0/ && (cd `dirname linux/HIDBootloader1.0.0` && $(TAR) HIDBootloader1.0.0.tar HIDBootloader1.0.0 && $(COMPRESS) HIDBootloader1.0.0.tar) && $(MOVE) `dirname linux/HIDBootloader1.0.0`/HIDBootloader1.0.0.tar.gz . && $(DEL_FILE) -r linux/HIDBootloader1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: linux/moc_Settings.cpp linux/moc_MainWindow.cpp linux/moc_Comm.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) linux/moc_Settings.cpp linux/moc_MainWindow.cpp linux/moc_Comm.cpp
linux/moc_Settings.cpp: Settings.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) Settings.h -o linux/moc_Settings.cpp

linux/moc_MainWindow.cpp: Comm.h \
		../HIDAPI/hidapi.h \
		Device.h \
		DeviceData.h \
		ImportExportHex.h \
		MainWindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) MainWindow.h -o linux/moc_MainWindow.cpp

linux/moc_Comm.cpp: ../HIDAPI/hidapi.h \
		Device.h \
		DeviceData.h \
		Comm.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) Comm.h -o linux/moc_Comm.cpp

compiler_rcc_make_all: linux/qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) linux/qrc_resources.cpp
linux/qrc_resources.cpp: resources.qrc \
		img/stop.png \
		img/BlankCheck.png \
		img/abort.png \
		img/writetqfp.png \
		img/Reset.png \
		img/erasetqfp.png \
		img/verify.png \
		img/open.png \
		img/help.png
	/usr/bin/rcc -name resources resources.qrc -o linux/qrc_resources.cpp

compiler_image_collection_make_all: linux/qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) linux/qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: linux/ui_MainWindow.h linux/ui_Settings.h
compiler_uic_clean:
	-$(DEL_FILE) linux/ui_MainWindow.h linux/ui_Settings.h
linux/ui_MainWindow.h: MainWindow.ui
	/usr/bin/uic-qt4 MainWindow.ui -o linux/ui_MainWindow.h

linux/ui_Settings.h: Settings.ui
	/usr/bin/uic-qt4 Settings.ui -o linux/ui_Settings.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

linux/Settings.o: Settings.cpp Settings.h \
		linux/ui_Settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linux/Settings.o Settings.cpp

linux/MainWindow.o: MainWindow.cpp MainWindow.h \
		Comm.h \
		../HIDAPI/hidapi.h \
		Device.h \
		DeviceData.h \
		ImportExportHex.h \
		linux/ui_MainWindow.h \
		Settings.h \
		../version.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linux/MainWindow.o MainWindow.cpp

linux/main.o: main.cpp MainWindow.h \
		Comm.h \
		../HIDAPI/hidapi.h \
		Device.h \
		DeviceData.h \
		ImportExportHex.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linux/main.o main.cpp

linux/DeviceData.o: DeviceData.cpp DeviceData.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linux/DeviceData.o DeviceData.cpp

linux/Device.o: Device.cpp Device.h \
		DeviceData.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linux/Device.o Device.cpp

linux/Comm.o: Comm.cpp Comm.h \
		../HIDAPI/hidapi.h \
		Device.h \
		DeviceData.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linux/Comm.o Comm.cpp

linux/ImportExportHex.o: ImportExportHex.cpp ImportExportHex.h \
		DeviceData.h \
		Device.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linux/ImportExportHex.o ImportExportHex.cpp

linux/moc_Settings.o: linux/moc_Settings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linux/moc_Settings.o linux/moc_Settings.cpp

linux/moc_MainWindow.o: linux/moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linux/moc_MainWindow.o linux/moc_MainWindow.cpp

linux/moc_Comm.o: linux/moc_Comm.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linux/moc_Comm.o linux/moc_Comm.cpp

linux/qrc_resources.o: linux/qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linux/qrc_resources.o linux/qrc_resources.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

